#!/usr/bin/env bash

# git
rm ~/.gitconfig
rm ~/.gitignore
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/gitignore ~/.gitignore

# shell
rm ~/.bash_aliases
rm ~/.profile
ln -s ~/dotfiles/aliases ~/.bash_aliases
ln -s ~/dotfiles/profile ~/.profile

source ~/.bashrc
source ~/.profile
echo ':: success ::'
