#!/usr/bin/env bash

rm ~/.profile
rm ~/.bashrc
rm -rf ~/.vim
rm -rf ~/.vimrc

ln -s ~/dotfiles/vim ~/.vim
ln -s ~/dotfiles/vim/vimrc ~/.vimrc
ln -s ~/dotfiles/profile ~/.profile
ln -s ~/dotfiles/bashrc ~/.bashrc

source ~/.profile
echo ':: success ::'